
import React from 'react';
import { Asset, AssetType, Language } from './types';
import { Landmark, Coins, Scale } from 'lucide-react';

export const ASSETS: Asset[] = [
  // Forex
  { id: 'f1', name: 'AUD/CAD', price: '0.91245', change: '+0.12%', type: AssetType.FOREX },
  { id: 'f2', name: 'AUD/CHF', price: '0.58432', change: '-0.45%', type: AssetType.FOREX },
  { id: 'f3', name: 'AUD/JPY', price: '98.421', change: '+0.23%', type: AssetType.FOREX },
  { id: 'f4', name: 'AUD/NZD', price: '1.08765', change: '-0.05%', type: AssetType.FOREX },
  { id: 'f5', name: 'AUD/USD', price: '0.65432', change: '+0.31%', type: AssetType.FOREX },
  { id: 'f6', name: 'CAD/CHF', price: '0.64123', change: '-0.12%', type: AssetType.FOREX },
  { id: 'f7', name: 'CAD/JPY', price: '111.452', change: '+0.18%', type: AssetType.FOREX },
  { id: 'f8', name: 'CHF/JPY', price: '172.105', change: '+0.09%', type: AssetType.FOREX },
  { id: 'f9', name: 'EUR/AUD', price: '1.64321', change: '-0.21%', type: AssetType.FOREX },
  { id: 'f10', name: 'EUR/CAD', price: '1.45678', change: '+0.15%', type: AssetType.FOREX },
  { id: 'f11', name: 'EUR/CHF', price: '0.94123', change: '-0.08%', type: AssetType.FOREX },
  { id: 'f12', name: 'EUR/GBP', price: '0.85432', change: '+0.04%', type: AssetType.FOREX },
  { id: 'f13', name: 'EUR/JPY', price: '162.145', change: '+0.32%', type: AssetType.FOREX },
  { id: 'f14', name: 'EUR/NZD', price: '1.78942', change: '-0.17%', type: AssetType.FOREX },
  { id: 'f15', name: 'EUR/SEK', price: '11.23410', change: '+0.42%', type: AssetType.FOREX },
  { id: 'f16', name: 'EUR/USD', price: '1.08450', change: '-0.11%', type: AssetType.FOREX },
  { id: 'f17', name: 'GBP/CAD', price: '1.70123', change: '+0.09%', type: AssetType.FOREX },
  { id: 'f18', name: 'GBP/CHF', price: '1.10432', change: '-0.23%', type: AssetType.FOREX },
  { id: 'f19', name: 'GBP/JPY', price: '189.654', change: '+0.51%', type: AssetType.FOREX },
  { id: 'f20', name: 'GBP/USD', price: '1.26543', change: '-0.03%', type: AssetType.FOREX },
  { id: 'f21', name: 'NZD/CAD', price: '0.81234', change: '+0.14%', type: AssetType.FOREX },
  { id: 'f22', name: 'NZD/JPY', price: '91.452', change: '-0.28%', type: AssetType.FOREX },
  { id: 'f23', name: 'USD/CAD', price: '1.35432', change: '+0.08%', type: AssetType.FOREX },
  { id: 'f24', name: 'USD/CHF', price: '0.87654', change: '-0.15%', type: AssetType.FOREX },
  { id: 'f25', name: 'USD/CNH', price: '7.21456', change: '+0.21%', type: AssetType.FOREX },
  { id: 'f26', name: 'USD/JPY', price: '150.842', change: '+0.42%', type: AssetType.FOREX },
  { id: 'f27', name: 'USD/MXN', price: '16.78452', change: '-0.52%', type: AssetType.FOREX },
  { id: 'f28', name: 'USD/NOK', price: '10.54321', change: '+0.33%', type: AssetType.FOREX },
  { id: 'f29', name: 'USD/SGD', price: '1.34123', change: '-0.04%', type: AssetType.FOREX },

  // Crypto
  { id: 'c1', name: 'BNB/USDT', price: '584.21', change: '+1.42%', type: AssetType.CRYPTO },
  { id: 'c2', name: 'BTC/USDT', price: '94210.50', change: '+2.14%', type: AssetType.CRYPTO },
  { id: 'c3', name: 'ETH/USDT', price: '2645.12', change: '+1.85%', type: AssetType.CRYPTO },
  { id: 'c4', name: 'LTC/USDT', price: '82.45', change: '-0.32%', type: AssetType.CRYPTO },
  { id: 'c5', name: 'MNT/USDT', price: '1.2415', change: '+5.12%', type: AssetType.CRYPTO },
  { id: 'c6', name: 'SOL/USDT', price: '142.12', change: '+3.42%', type: AssetType.CRYPTO },
  { id: 'c7', name: 'XAUT/USDT', price: '2341.20', change: '+0.31%', type: AssetType.CRYPTO },
  { id: 'c8', name: 'XRP/USDT', price: '0.6124', change: '-1.12%', type: AssetType.CRYPTO },
  { id: 'c9', name: 'ZEC/USDT', price: '28.45', change: '-2.14%', type: AssetType.CRYPTO },

  // Metals
  { id: 'm1', name: 'GOLD', price: '2341.22', change: '+0.34%', type: AssetType.METALS },
  { id: 'm2', name: 'SILVER', price: '31.154', change: '-0.12%', type: AssetType.METALS },
  { id: 'm3', name: 'PLATINUM', price: '984.12', change: '+1.12%', type: AssetType.METALS },
  { id: 'm4', name: 'PALLADIUM', price: '1024.50', change: '-0.85%', type: AssetType.METALS },
];

export const TIMEFRAMES = [
  '1 мин', '2 мин', '5 мин',
  '10 мин', '15 мин', '30 мин',
  '1 час', '4 часа', '1 день'
];

export const TAB_ICONS = {
  [AssetType.FOREX]: <Landmark size={14} />,
  [AssetType.CRYPTO]: <Coins size={14} />,
  [AssetType.METALS]: <Scale size={14} />,
};

export const TRANSLATIONS: Record<Language, any> = {
  RU: {
    heroTitle: "ИНТЕЛЛЕКТУАЛЬНЫЙ ТРЕЙДИНГ",
    heroAccent: "INFINITY TRAFFIC",
    heroDesc: "Профессиональная аналитическая платформа на базе ИИ. Получайте сверхточные сигналы в реальном времени для Forex, Криптовалют и Металлов.",
    statusLabel: "ВАШ УРОВЕНЬ",
    limitsLabel: "ДОСТУПНЫЕ ЛИМИТЫ",
    startBtn: "НАЧАТЬ ТОРГОВЛЮ",
    historyTitle: "ИСТОРИЯ СДЕЛОК",
    historyEmpty: "История пуста",
    selectAssetTitle: "ВЫБЕРИТЕ ИНСТРУМЕНТ",
    selectAssetDesc: "Выберите актив для проведения глубокого анализа нейросетью",
    selectTfTitle: "ВЫБОР ПЕРИОДА",
    backToMenu: "НАЗАД",
    analyzing: "АНАЛИЗ РЫНКА...",
    signalBuy: "ВЫШЕ",
    signalSell: "НИЖЕ",
    confirmed: "УСПЕШНО",
    failed: "НЕУДАЧА",
    newCycle: "НОВЫЙ АНАЛИЗ",
    backToDashboard: "В ЛИЧНЫЙ КАБИНЕТ",
    accuracy: "ВЕРОЯТНОСТЬ",
    unlimited: "БЕЗЛИМИТНЫЙ",
    forexOnly: "Для доступа к Крипто и Металлам необходим уровень VIP",
    limitReached: "Лимит сигналов исчерпан. Обновление каждые 12 часов.",
    supportBtn: "ПОДДЕРЖКА",
    enterPw: "ВВЕДИТЕ ПАРОЛЬ ДОСТУПА",
    wrongPw: "НЕВЕРНЫЙ ПАРОЛЬ",
    statusStandard: "СТАНДАРТ",
    statusVerified: "ВЕРИФИЦИРОВАН",
    statusVip: "VIP ЭЛИТА",
    changeStatus: "ИЗМЕНИТЬ УРОВЕНЬ",
    searchAsset: "ПОИСК АКТИВА...",
    priceLabel: "КОТИРОВКА",
    pageLabel: "СТРАНИЦА",
    tfDesc: "Выберите временной интервал для построения прогноза",
    analysisStage: "ЗАПУСК КВАНТОВОГО ЯДРА",
    analysisDesc: "СИНХРОНИЗАЦИЯ С РЫНКОМ...",
    confidenceLabel: "ИНДЕКС ДОВЕРИЯ",
    alphaStream: "ALPHA SIGNAL",
    quantumVerified: "QUANTUM VERIFIED",
    modalTitle: "СМЕНА ТИПА АККАУНТА",
    modalConfirm: "ПОДТВЕРДИТЬ",
    realTime: "В РЕАЛЬНОМ ВРЕМЕНИ",
    marketClosed: "РЫНОК ЗАКРЫТ",
    newsMonitoring: "МОНИТОРИНГ НОВОСТЕЙ",
    investingSource: "ИСТОЧНИК: INVESTING.COM",
    highImpact: "ВЫСОКИЙ",
    medImpact: "СРЕДНИЙ",
    lowImpact: "НИЗКИЙ",
    GOLD: "ЗОЛОТО",
    SILVER: "СЕРЕБРО",
    PLATINUM: "ПЛАТИНА",
    PALLADIUM: "ПАЛЛАДИЙ",
    lockedAsset: "АКТИВ ЗАБЛОКИРОВАН"
  },
  EN: {
    heroTitle: "INTELLIGENT TRADING",
    heroAccent: "INFINITY TRAFFIC",
    heroDesc: "Professional AI-powered analytical platform. Get ultra-precise real-time signals for Forex, Crypto, and Metals.",
    statusLabel: "ACCOUNT TYPE",
    limitsLabel: "AVAILABLE LIMITS",
    startBtn: "START TRADING",
    historyTitle: "TRADE HISTORY",
    historyEmpty: "History is empty",
    selectAssetTitle: "SELECT INSTRUMENT",
    selectAssetDesc: "Select an asset for deep neural network analysis",
    selectTfTitle: "SELECT PERIOD",
    backToMenu: "BACK",
    analyzing: "MARKET ANALYSIS...",
    signalBuy: "CALL",
    signalSell: "PUT",
    confirmed: "SUCCESS",
    failed: "FAILED",
    newCycle: "NEW ANALYSIS",
    backToDashboard: "TO DASHBOARD",
    accuracy: "PROBABILITY",
    unlimited: "UNLIMITED",
    forexOnly: "VIP level required for Crypto and Metals",
    limitReached: "Signal limit reached. Resets every 12 hours.",
    supportBtn: "SUPPORT",
    enterPw: "ENTER ACCESS PASSWORD",
    wrongPw: "INCORRECT PASSWORD",
    statusStandard: "STANDARD",
    statusVerified: "VERIFIED",
    statusVip: "VIP ELITE",
    changeStatus: "CHANGE TYPE",
    searchAsset: "SEARCH ASSET...",
    priceLabel: "QUOTE",
    pageLabel: "PAGE",
    tfDesc: "Select timeframe for forecast generation",
    analysisStage: "QUANTUM CORE LAUNCH",
    analysisDesc: "MARKET SYNC...",
    confidenceLabel: "CONFIDENCE INDEX",
    alphaStream: "ALPHA SIGNAL",
    quantumVerified: "QUANTUM VERIFIED",
    modalTitle: "CHANGE ACCOUNT TYPE",
    modalConfirm: "CONFIRM",
    realTime: "REAL-TIME",
    marketClosed: "MARKET CLOSED",
    newsMonitoring: "NEWS MONITORING",
    investingSource: "SOURCE: INVESTING.COM",
    highImpact: "HIGH",
    medImpact: "MEDIUM",
    lowImpact: "LOW",
    GOLD: "GOLD",
    SILVER: "SILVER",
    PLATINUM: "PLATINUM",
    PALLADIUM: "PALLADIUM",
    lockedAsset: "LOCKED ASSET"
  }
};
